posts:
  - how-to-use-ruby-like-php                        2012-09-08
  - pygments-rb                                     2012-09-11
  - recovering-from-segfaults-in-ruby               2012-11-20
  - changing-the-superclass-of-a-class-in-ruby      2012-12-14
  - why-do-singleton-methods-make-ruby-slow         2012-12-18
  - rails-3.2.10-remote-code-execution              2013-01-10
  - things-that-clear-rubys-method-cache            2013-03-30
code:
  - title: better_errors
    link: https://github.com/haileysome/better_errors
    tags:
      - ruby
    description:
      "A better error page for Rails and other Rack apps. Includes source code inspection, a live REPL and local/instance variable inspection for all stack frames."
  -
    title: eval.in
    link: http://eval.in/
    tags:
      - ruby
      - c
    description:
      "An online code pastebin/evaluator that can execute code written in Ruby, PHP, Python, Lua, IO, Perl and JavaScript."
  - title: rustboot
    link: https://github.com/haileysome/rustboot
    tags:
      - rust
    description:
      "A tiny proof of concept 32 bit kernel in Rust."
  -
    title: Slash
    link: https://github.com/slash-lang/slash
    tags:
      - c
    description:
      "A work-in-progress language designed with the goal of being a sane PHP replacement. Ruby object model and semantics, Perl/Ruby-ish syntax, PHP execution model."
  -
    title: Racer
    link: https://github.com/haileysome/racer
    tags:
      - c
    description:
      "A high performance Ruby web server written in C using libuv and node.js's HTTP parser. Faster than Thin, Puma and Unicorn."
  - title: ptydo
    link: https://github.com/haileysome/ptydo
    tags:
      - c
    description:
      "Runs a program in its own pseudo-terminal exposed as stdin/stdout"
  - title: JSOS
    link: https://github.com/haileysome/jsos
    tags:
      - c
      - javascript
      - coffeescript
    description:
      "A JavaScript operating system that uses a simple JavaScript VM I wrote. All drivers and most kernel code is written in JavaScript. The userland is entirely JavaScript and CoffeeScript."
  - title: Twostroke
    link: https://github.com/haileysome/twostroke
    tags:
      - ruby
      - javascript
    description:
      "A JavaScript implementation written in Ruby. Complete enough to run the CoffeeScript compiler and pass all underscore.js tests."
  - title: diffcalc
    link: http://haileysome.github.com/diffcalc
    tags:
      - javascript
    description:
      "A differential calculator written in JavaScript."
