development:
  db:
    adapter: mysql2
    host: localhost
    username: root
    database: charlie-bz
production:
  db:
    adapter: mysql2
    host: localhost
    username: root
    database: charlie-bz